### PR TITLE
Cleanup the repository from obsoleted files #20

### PR DESCRIPTION
**Pull request by iloveeclipse**

### CODE REVIEW

**Comment by KengoTODA** [comment]
> bugDescriptions_fr.html

Currently new manual site has no bug description page in French. And I'm sure that [messages_fr.xml](https://github.com/spotbugs/spotbugs/blob/master/spotbugs/etc/messages_fr.xml) is also not maintained.

I guess that it's necessary to drop French support? If so, we need to delete not only this file but also [hyperlink in `index.html`](https://github.com/spotbugs/spotbugs.github.io/blob/e8609c2/index.html#L41).
Sorry but I'm not sure we have French speaker in contributors or not...

**Comment by KengoTODA** [comment]
FYI: One more document we have at [spotbugs/src/doc](https://github.com/spotbugs/spotbugs/tree/master/spotbugs/src/doc) directory, but I'm not sure it is also obsoleted or not. Let's handle them in different topic.

**Comment by iloveeclipse** [comment]
If I understood it right, the files which I've deleted here are copied from the main project repo and not used for building manual at all. I see no value to have obsoleted files which are not used for manual generation anyway.

**Comment by iloveeclipse** [comment]
@KengoTODA : I apologize, I've somehow managed to push the amended commit directly to master instead to the cleanup branch. Is this OK, or should I revert my last commit?

In the last commit I've removed the link to the French translation.

**Comment by KengoTODA** [comment]
@iloveeclipse it should have no problem, I'll close this PR.

**Pull request closed without merging**
