### PR TITLE
add eclipse update site for 3.1.0-RC3

### PR DESCRIPTION
**Pull request by KengoTODA**
same with #14, but fixed pointed problems at there

### CODE REVIEW

**Comment by iloveeclipse** [comment]
@sewe: can you please re iew this? I'm pretty busy right now.

**Comment by sewe** [comment]
@iloveeclipse I can have a look, but I couldn’t get the invitation you sent me earlier to work:

> Sorry, we couldn't find that repository invitation. It is possible that the invitation was revoked or that you are not logged into the invited account.

**Comment by iloveeclipse** [comment]
@sewe : can you access the repo or not? I have no idea how github manages access rights here. @KengoTODA : can you help here? I think the repo is public one, isn't?

**Comment by sewe** [comment]
> @sewe can you access the repo or not? I have no idea how github manages access rights here. 

I can read/clone the repo just fine. I just can’t accept the invitation.

**Comment by iloveeclipse** [comment]
A-ha, I think this was me playing with the github project, sorry for that noise. I've tried to add you but this didn't helped and github was not showing your name, so I've cancelled this.

**Comment by KengoTODA** [comment]
@iloveeclipse To add members, we need to ask admin to add at [collaboration setting page](https://github.com/spotbugs/spotbugs.github.io/settings/collaboration). I'm just a member so I cannot handle it, maybe you, @mebigfatguy or @jsotuyod can handle.

**Comment by KengoTODA** [comment]
For now this repository doesn't require review to merge. So if you or @sewe confirmed this PR has no problem, I can merge this by own.

**Comment by KengoTODA** [comment]
Hello, can I merge this PR?

**Comment by iloveeclipse** [comment]
@KengoTODA : how I can verify the change?

**Comment by KengoTODA** [comment]
Most easiest way is pull this branch and host it in local. I use [http-server](https://www.npmjs.com/package/http-server) for this kind of cases.

**Comment by iloveeclipse** [comment]
OK, thanks, I've checked this now. What exact should I verify? Eclipse install works, but the plugin is a bit too old (February 25). So if this is just as a placeholder for the Eclipse marketplace, we can push it.

**Comment by KengoTODA** [comment]
Feb 25? Wmm, it's strange, the jar filename is `3.1.0.20170610-1497060633070.jar`...

**Comment by KengoTODA** [comment]
I've tested again but couldn't reproduce.

Anyway, I'll merge this, and ask Eclipse marketplace to host our plugin. Thanks for your help!

**Comment by iloveeclipse** [comment]
@KengoTODA : which URL will it be and shouldn't we link this from the front page?

**Comment by KengoTODA** [comment]
@iloveeclipse Thanks for your reminder, I've proposed #17 to add.

**Pull request merged**
