### PR TITLE
Release 3.1.0-RC2 to eclipse update site

### PR DESCRIPTION
**Pull request by KengoTODA**
This PR updates `eclipse-candidate` update site, and adds `eclipse` update site.
Both of them will host 3.1.0-RC2 version.

3.1.0-RC2 is not stable version yet, but we need to push update site to [stable channel](https://spotbugs.github.io/eclipse/) or we cannot finish making [Eclipse marketplace page](https://marketplace.eclipse.org/content/spotbugs-eclipse-plugin) ready.

@iloveeclipse Please review this change. I found that `artifacts.xml` contains local path like `file:/home/ubuntu/spotbugs/`, is it OK? Previously I've confirmed that `eclipse-candidate` update site works well, though.

### CODE REVIEW

**Comment by iloveeclipse** [comment]
Do we really want to put generated plugin artifacts into source repository? I personally don't like this approach.

Beside this, can you please simply attach all the generated stuff in a zip so that I could try to install it into the IDE?

**Comment by iloveeclipse** [comment]
I'm sorry, I thought it is the source code repo, I see now this is the site itself.

**Comment by iloveeclipse** [comment]
Feature description still mentions FindBugs: "This feature is a wrapper for the FindBugs plugin for installation via the Eclipse Update Manager."

**Review by iloveeclipse — CHANGES_REQUESTED** [review]
The generated jar files AND versions inside them have wrong version: 3.1.**02**.20170516. Note the wrong "02" version (it should be 3.1.0, not 3.1.02).

Also site.xml has this issue, but NOT the artifacts/content files, which have 3.1.**2**.

**Comment by KengoTODA** [comment]
Thanks, I've proposed https://github.com/spotbugs/spotbugs/issues/173 to fix this problem.

**Comment by KengoTODA** [comment]
It is better to regenerate update site, because this `version` is used even in plugin jar file. I will create another PR after we release RC3 or 3.1.0.

**Pull request closed without merging**
