### PR TITLE
Release 3.1.0-RC4

### PR DESCRIPTION
**Pull request by KengoTODA**
This PR will add files to let users install latest SpotBugs plugin to their Eclipse.

### CODE REVIEW

**Review by iloveeclipse — CHANGES_REQUESTED** [review]
The artifacts.xml and content.xml are not updated, so Eclipse still tries to install old version.

**Comment by KengoTODA** [comment]
Oops, then it should be problem of `build.groovy`. I will fix this problem in RC5.

**Comment by iloveeclipse** [comment]
But shouldn't we release RC4 as Eclipse plugin? You just need to manually add two missing files to the commit?

**Comment by KengoTODA** [comment]
I can't make it manually. Could you help?

**Comment by iloveeclipse** [comment]
I've pushed #30 , please review.

**Pull request closed without merging**
